CREATE DATABASE IF NOT EXISTS `C-SCORE` DEFAULT CHARACTER SET UTF8MB4 COLLATE utf8_general_ci;
USE `C-SCORE`;

CREATE TABLE `ACCESS_TO` (
  `reference` VARCHAR(42),
  `last_name` VARCHAR(42),
  PRIMARY KEY (`reference`, `last_name`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `ACCESS_TO1` (
  `label` VARCHAR(42),
  `last_name` VARCHAR(42),
  PRIMARY KEY (`label`, `last_name`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `BIDDER` (
  `name` VARCHAR(42),
  `description` VARCHAR(42),
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `CHAPTER` (
  `label` VARCHAR(42),
  `order` VARCHAR(42),
  `last_name` VARCHAR(42),
  `label_1` VARCHAR(42),
  PRIMARY KEY (`label`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `FOLDER` (
  `reference` VARCHAR(42),
  `label` VARCHAR(42),
  `description` VARCHAR(42),
  `status` VARCHAR(42),
  `last_name` VARCHAR(42),
  PRIMARY KEY (`reference`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `HAS` (
  `reference` VARCHAR(42),
  `label` VARCHAR(42),
  PRIMARY KEY (`reference`, `label`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `HAS1` (
  `label` VARCHAR(42),
  `label_1` VARCHAR(42),
  PRIMARY KEY (`label`, `label_1`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `HAS2` (
  `label` VARCHAR(42),
  `label_1` VARCHAR(42),
  PRIMARY KEY (`label`, `label_1`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `LINKED_TO` (
  `reference` VARCHAR(42),
  `name` VARCHAR(42),
  PRIMARY KEY (`reference`, `name`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `QUESTION` (
  `label` VARCHAR(42),
  `moderation` VARCHAR(42),
  `order` VARCHAR(42),
  `last_name` VARCHAR(42),
  PRIMARY KEY (`label`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `RESPONSE` (
  `moderation` VARCHAR(42),
  `comment` VARCHAR(42),
  `label` VARCHAR(42),
  PRIMARY KEY (`moderation`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `SECTION` (
  `label` VARCHAR(42),
  `description` VARCHAR(42),
  `order` VARCHAR(42),
  PRIMARY KEY (`label`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `USER` (
  `last_name` VARCHAR(42),
  `first_name` VARCHAR(42),
  `email` VARCHAR(42),
  `role` VARCHAR(42),
  `label` VARCHAR(42),
  PRIMARY KEY (`last_name`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE `ACCESS_TO` ADD FOREIGN KEY (`last_name`) REFERENCES `USER` (`last_name`);
ALTER TABLE `ACCESS_TO` ADD FOREIGN KEY (`reference`) REFERENCES `FOLDER` (`reference`);
ALTER TABLE `ACCESS_TO1` ADD FOREIGN KEY (`last_name`) REFERENCES `USER` (`last_name`);
ALTER TABLE `ACCESS_TO1` ADD FOREIGN KEY (`label`) REFERENCES `SECTION` (`label`);
ALTER TABLE `CHAPTER` ADD FOREIGN KEY (`label_1`) REFERENCES `CHAPTER` (`label`);
ALTER TABLE `CHAPTER` ADD FOREIGN KEY (`last_name`) REFERENCES `USER` (`last_name`);
ALTER TABLE `FOLDER` ADD FOREIGN KEY (`last_name`) REFERENCES `USER` (`last_name`);
ALTER TABLE `HAS` ADD FOREIGN KEY (`label`) REFERENCES `SECTION` (`label`);
ALTER TABLE `HAS` ADD FOREIGN KEY (`reference`) REFERENCES `FOLDER` (`reference`);
ALTER TABLE `HAS1` ADD FOREIGN KEY (`label_1`) REFERENCES `CHAPTER` (`label`);
ALTER TABLE `HAS1` ADD FOREIGN KEY (`label`) REFERENCES `SECTION` (`label`);
ALTER TABLE `HAS2` ADD FOREIGN KEY (`label_1`) REFERENCES `QUESTION` (`label`);
ALTER TABLE `HAS2` ADD FOREIGN KEY (`label`) REFERENCES `CHAPTER` (`label`);
ALTER TABLE `LINKED_TO` ADD FOREIGN KEY (`name`) REFERENCES `BIDDER` (`name`);
ALTER TABLE `LINKED_TO` ADD FOREIGN KEY (`reference`) REFERENCES `FOLDER` (`reference`);
ALTER TABLE `QUESTION` ADD FOREIGN KEY (`last_name`) REFERENCES `USER` (`last_name`);
ALTER TABLE `RESPONSE` ADD FOREIGN KEY (`label`) REFERENCES `QUESTION` (`label`);
ALTER TABLE `USER` ADD FOREIGN KEY (`label`) REFERENCES `SECTION` (`label`);